### ISSUE TITLE
Some questions about visualization of HOI4D action segmentation task

### ISSUE THREAD

**Issue by Ananwang2002** [dongyh20/C2P#1]
Hi,  we noticed that the visualizations of the action segmentation tasks in your paper contained very dense points. In our attempts, we found that there are only 2048 points per frame. Could you tell us what operations you performed in the visualizations?

**Comment by dongyh20** [comment]
Thanks for your interest in our work! To better illustrate the effectiveness of our strategy, the point clouds in the teaser and method picture are not downsampled. We use the raw point cloud obtained from depth image and perform our strategy. For action segmentation experiments, we use 2048 point cloud as stated in the paper. Visualization is just used to convey our idea more straightforward. Any other questions are welcomed!
